### ISSUE TITLE
iCloud Music Library playlists can only contain songs from your iCloud Music Library

### ISSUE THREAD

**Issue by wviana** [ryanb93/Applefy#12]
when adding the musics, when I click "Remove playlist and continue" it does not sync to iCloud music library, so it does not show in iPhone. I did share the playlist link than open in iPhone to have it in my iPhone.
PS: Where is the strings plist? I may translate to Portuguese for you. PS2: The facebook login works :D

<img width="602" alt="zkntjuo jpg" src="https://cloud.githubusercontent.com/assets/1062631/8640175/987bdfa0-28c5-11e5-8a9f-fdc8e0ecbcf4.png">

**Comment by ryanb93** [comment]
You need to then right click on all of the songs from within iTunes and select 'Add to iCloud Music Library', this will then start the syncing process for songs that can be matched by iTunes.

We don't currently have a strings plist, i'll look at converting it.
