### ISSUE TITLE
All songs are coming through as 5 second silent clips

### ISSUE THREAD

**Issue by alexdelabright** [ryanb93/Applefy#14]
None of my songs are coming through correctly for some reason. I know this issue has been reported if iTunes doesn't have the matching song in their database but that's not the case with all of my music library. 
Any fix for this?

Thanks

**Comment by ryanb93** [comment]
Do you have iTunes Match? It does not work with it.

**Comment by mmffdev** [comment]
HI Ryan, great job btw! I think i'm having the same issue, in iTunes all the tracks say .05 yet they play.. Could be doing something wrong my end.. 

Cheers!

**Comment by jooize** [comment]
I have this issue with some tracks, but not all. Applefy is _way_ quicker than using [MovetoAppleMusic](http://movetoapple.com/), so thank you for that. I want to be rid of this 5-second track issue though.

What does having iTunes Match mean and can I disable that if I only use Apple Music? I thought they were pretty much intertwined.
