### ISSUE TITLE
Facebook-Login Support?

### ISSUE THREAD

**Issue by martinseener** [ryanb93/Applefy#17]
Hi,

i wanted to use Applefy today but i don't know which user/pass combination i have to use since i always login to spotify using facebook. Is this supported?

If Applefy works afterwards (i also have iTunes Match) a donation will be made for your efforts creating this app ;)

Martin

**Comment by ryanb93** [comment]
Hi,

You can log in with your Facebook email and password, this will work. If you have two-factor authentication then the login will fail but then you should receive An SMS with a code, so use that.

Thanks 

Ryan

**Comment by martinseener** [comment]
Uh, thanks alot! I think we can close this here then. Donation is coming when i finished migrating.
