### ISSUE TITLE
Can't get rid of the 5 second thing..

### ISSUE THREAD

**Issue by lbink** [ryanb93/Applefy#18]
Great work ant thaks for creating a straightforward solution for importig playlists into Apple Music.

Sadly, I am stuck with the 5 seconds of silence....

I have created an extra apple account (family member (and thus apple music subscriber), but no itunes Match).
If I import the playlist, add the songs to the iCloud music library and finally delete the downloaded files, I am still stuck with the 5 seconds of silence. The songs do exist in apple music. Artwork is downloaded..

If I share the playlist created in iTunes with another account, I comes up empty.
Exporting the playlist, deleting the content from the library, and importing the playlist reults in an empty playlist as well. With iTunes complaining it cannot find the tracks.

Manually searching for the songs gives me the correct track.

(iTunes 12.3.0.44 on OSX 10.11.1)

What am I doing wrong?

Cheers!

**Comment by jaredatron** [comment]
It looks like "add to iCloud music" has been changed to upload the track :(

**Comment by michaeljohansen** [comment]
So, this app is currently not working due to changes in iTunes/iCloud music? Any thoughts on workarounds?

**Comment by ryanb93** [comment]
@michaeljohansen what happens if you share the playlist to generate a URL, delete the playlist locally and then access the URL again? (I would try but I canceled by Apple Music subscription)

**Comment by michaeljohansen** [comment]
Sorry mate, I already performed the move using a similar app. I don't have time to recreate the environment to test it atm.

**Comment by rogerchinchilla** [comment]
Garbage. Delete this repo.

**Comment by jaredatron** [comment]
Is this ever going to get fixed? Maybe you should delete the repo?

**Comment by ryanb93** [comment]
@deadlyicon - I don't delete repositories of code because they no longer work, they are a showcase of my work and allow other people to build on it.

I no longer have an Apple Music subscription so I can not test the code to try and fix it. If Apple has closed the 5 second song workaround then that is outside of my control. The best I can do is remove the binary download and update the README to show that the project is depricated, but I won't be removing it from GitHub.

**Comment by jaredatron** [comment]
https://github.com/ryanb93/Applefy/pull/20
