### ISSUE TITLE
Problems with special characters

### ISSUE THREAD

**Issue by omBratteng** [ryanb93/Applefy#2]
Any song that contains a special character is exported like this:
https://www.dropbox.com/s/3zp03caxw96s2r7/Skjermbilde%202015-07-10%2009.34.59.png?dl=0

**Comment by ryanb93** [comment]
This has been fixed in the latest version, thank you.

**Comment by omBratteng** [comment]
That's great!!
I'll download the latest version as soon as I get home

## 

Martin Bratteng
http://bratteng.me
