### ISSUE TITLE
5 Second Song

### ISSUE THREAD

**Issue by simchal123** [ryanb93/Applefy#5]
Everything has been successful so far, I've added the songs to my iCloud Music Library, removed the download and then downloaded them again. But if I don't want to make the whole playlist available offline and I remove the downloads again, it says the song is 5 second long. The song still plays, but it won't let me skip along the song or anything, I have to download it to do so. My question is, is there a way to make it have (or make it think it has) the full length of the song?

Thank you very much for the help by the way. I'll be sure to buy you a coffee as soon as I'm not broke 😇

**Comment by mikkelnl** [comment]
Same question/issue here ;)

**Comment by DAddYE** [comment]
Same here

**Comment by einfallstoll** [comment]
+1

**Comment by ryanb93** [comment]
There is not really a nice way to fix this without creating a new MP3 for every song with the same length as the Spotify song. This data can be accessed using 

```
track.duration
```

But this may still not match up with the iTunes version. This could be done so that instead of copying the '5sec.mp3" for each song - something like LAME could be used to generate a new MP3 but not sure how to implement this at the moment.

**Comment by einfallstoll** [comment]
@ryanb93 In `TagLib::MPEG::Properties` there's a `length` property. Maybe it's possible to set this one instead fo generating a new one? I mean iTunes plays a song which has 5 seconds for several minutes.

In the end I assume this is a bug from iCloud…

**Comment by ryanb93** [comment]
@einfallstoll I believe that "audioProperties" are read only.

**Comment by einfallstoll** [comment]
@ryanb93 And I believe that I just found a solution :smiley: I'm testing right now and come back later…

**Comment by einfallstoll** [comment]
Ok, I think I know the problem now:

When uploading / matching songs the metadata from the local .mp3 are used and the remaining fields are filled by iCloud. As long as the file gets streamed iCloud will use the previously added metadata (including the duration of 5 secs). As soon as you download the file from Apple Music, iTunes will use the metadata stored in the media file with the correct duration.

This means it's a bug of the iCloud matching. 

**Update:** I filed a bug report regarding this issue and keep you updated if I know anything new.

**Comment by DAddYE** [comment]
if we don't import the length in the metadata or we grab it from Spotify ?

**Comment by einfallstoll** [comment]
@DAddYE The Spotify API actually let us know the duration of the song, we'd have to create a new empty MP3 for every single song, which would not only be time consuming but also would take long to upload the missing files to iCloud. At the moment I don't think this is a solution especially if you have a large music library with lots of songs not available in Apple Music. And even if we did this, the problem would still occur (even though less often) when the Spotify duration doesn't met the Apple Music duration.

**Comment by DAddYE** [comment]
Oh I see. Can't you give us an option to download the entire mp3?

**Comment by ryanb93** [comment]
@DAddYE You can but it's against the Spotify terms of service and my developer key will be blocked. It's what pySpotify first did, but you have to wait for every song to play so you can pipe the audio to a file. So you have to wait 3 minutes every song. Not ideal.

**Comment by lukens** [comment]
I'm unable to get anything other than 5 seconds of silence no matter what I do.

I've followed the instruction, but when adding to my Apple music, it seems to always upload the 5 seconds of silence, so when I download again, it's still just 5 seconds of silence.

I'm wondering it this is because I also have iTunes Match, but can't find a way to switch that off.

I don't think it's because my playlist is full of obscure songs not available on Apple Music.

**Comment by ryanb93** [comment]
@lukens Yup this is because of iTunes Match, some people have had success with directly contacting Apple support and stopping their Match subscription with immediate effect.

**Comment by lukens** [comment]
Hmm, I guess I could do this on a second computer with a second (non iTunes match) account, and then share the playlist.

Do you know if I cancel my iTunes match account whether I will lose all matched songs not currently on my computer?

**Comment by neilio** [comment]
I'm glad someone opened this because the 5 second of silence thing was driving me crazy, too. So the fix is to contact apple and have them remove iTunes Match from the account completely?

**Comment by nitinsavant** [comment]
@ryanb93 @lukens @neilio I'm experiencing the same issue, but I've never subscribed to iTunes Match.

UPDATE: Making progress.
- After dragging the files into an iTunes playlist, every song is 0:05 and plays silence.
- After right-clicking and selecting "Add to iCloud Music Library", each song is 0:05 and plays silence.
- After right-clicking and selecting "Remove Download", each song is 0:05 but the song now plays!
- After right-clicking and selecting "Make Available Offline", the song's lengths are fixed!

But if you "Remove Download", the song returns to 0:05. I'll run out of space quickly on my Mac if I have to make every song available offline. Any ideas?

UPDATE2: After you play the songs, the correct lengths tend to show up. I learned a bunch by browsing this Reddit thread: https://www.reddit.com/r/apple/comments/3cpcbv/applefy_20_spotify_playlist_to_music_native/

**Comment by lukens** [comment]
@nitinsavant Unfortunately, if you have iTunes Match, it goes like this:
- After dragging the files into an iTunes playlist, every song is 0:05 and plays silence.
- After right-clicking and selecting "Add to iCloud Music Library", each song is 0:05 and plays silence.
- After right-clicking and selecting "Remove Download", each song is 0:05 and plays silence.
- After right-clicking and selecting "Make Available Offline", each song is 0:05 and plays silence.

**Comment by alessandroorru** [comment]
read this on reddit, it works for me:

https://www.reddit.com/r/apple/comments/3cpcbv/applefy_20_spotify_playlist_to_music_native/ct62jls

**Comment by Teumer** [comment]
Second to the last step: Select all and right click. Choose 'Add to iCloud Music Library'

I do not have the option to add to iCloud Music Library. I can play, get info, love, get album artwork, etc, however, this option is missing. What can I do?
