### ISSUE TITLE
Any way to match playlist order?

### ISSUE THREAD

**Issue by neilio** [ryanb93/Applefy#7]
This is great work (but) but the one issue I've run into is when it saves the MP3s the track order in the original playlist is lost - it's organized alphabetically. Could you add a # prefix to each file name so the playlist order can be maintained?

**Comment by nicholaspeshek** [comment]
I've got an open pull request adding that if you want to try it out that would be fantastic.

**Comment by ryanb93** [comment]
Merged fix.
