### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by einfallstoll** [ryanb93/Applefy#9]
It's not possible to check out your project without manually search and download the dependencies (`CocoaLibSpotify` and `TagLib`). They're currently relatively linked outside the repository (e.g. `../CocoaLibSpotify`).

They should be included in the repository as well (to match the same version) or added via a submodule.

---

**Update**:

`TagLib`: `/Users/Ryan/Developer/cocoalibspotify/Mac Framework/../../TagLib/TagLib.framework/TagLib.xcodeproj`
`CocoaLibSpotify`: `../cocoalibspotify/Mac Framework/CocoaLibSpotify Mac Framework.xcodeproj`

**Comment by MartinAyla** [comment]
When I try and build the project, Xcode want to fetch the two libraries, but I can't seem to authenticate to Github - any ideas?

**Comment by einfallstoll** [comment]
Not tested, but this should work:

```
git clone https://github.com/ryanb93/Applefy.git
git submodule init
git submodule update
```

**Comment by MartinAyla** [comment]
That worked, thanks.

I've noticed two things in the latest version;
1. Playlist names aren't showing (blank)
2. The 'buy me a coffee' button doesn't move when you resize the window, so it overlays the other text

**Comment by ryanb93** [comment]
@MartinAyla the playlist names are showing up fine for me, can't replicate this. I'll fix the coffee button.

**Comment by MartinAyla** [comment]
@ryanb93 This is how it looks for me, git clone from 15min ago and build in Xcode:
![screen shot 2015-07-13 at 11 53 03](https://cloud.githubusercontent.com/assets/3063746/8647183/fb579aac-2955-11e5-8ce4-087e9b95c2b5.jpg)

**Comment by ryanb93** [comment]
That's strange behaviour. The logic for setting that playlist is:

```
[SPAsyncLoading waitUntilLoaded:aSession timeout:kSPAsyncLoadingDefaultTimeout then:^(NSArray *loaded, NSArray *notLoaded) {
    [SPAsyncLoading waitUntilLoaded:aSession.userPlaylists timeout:kSPAsyncLoadingDefaultTimeout then:^(NSArray *loaded, NSArray *notLoaded) {
        [self setFlatPlaylists:aSession.userPlaylists.flattenedPlaylists];
        [self.playlistButton setEnabled:YES];
    }];
}];
```

The setFlatPlaylists must be working but it seems like the UI isn't able to access the playlist names to generate the titles. Not seen anyone else with this issue though, what version of OS X are you running?

**Comment by MartinAyla** [comment]
I'm not a programmer, but can it be special characters in playlist names maybe?

I'm using 10.10.4, and I'm just hitting 'build and run' in Xcode.

Using @einfallstoll's guide for downloading first:

git clone https://github.com/ryanb93/Applefy.git
git submodule init
git submodule update

**Comment by ryanb93** [comment]
@MartinAyla Potentially, could you screenshot your playlist names as shown in the Spotify app?

**Comment by MartinAyla** [comment]
@ryanb93 I just did a new 'build and run' and now the names are showing, strange. I'll let you know if it happens again.
